#!/bin/sh

# SITE INFORMATION
URL="https://example.com"
LANG="en-us"
AUTHOR="Your Name"
SITETITLE="Example Website"
KEYWORDS="Blog, Writing, Websites"
DESC="A simple website"

# BUILDER PATH
ROOT="."

# OUTPUT PATH 
SITE="$ROOT/out/"
